#!/usr/bin/env python3
"""Script to check training plans and workouts in the database"""

import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.core.database import SessionLocal
from app.models import TrainingPlan, Workout, User, Goal

def check_plans():
    """Check all training plans and their workouts"""
    db = SessionLocal()
    try:
        # Get all training plans
        plans = db.query(TrainingPlan).all()

        print(f"\n{'='*80}")
        print(f"TRAINING PLANS DIAGNOSTIC")
        print(f"{'='*80}\n")

        if not plans:
            print("❌ No training plans found in database")
            return

        print(f"Found {len(plans)} training plan(s):\n")

        for plan in plans:
            user = db.query(User).filter(User.id == plan.user_id).first()
            goal = db.query(Goal).filter(Goal.id == plan.goal_id).first()
            workouts = db.query(Workout).filter(Workout.training_plan_id == plan.id).all()

            print(f"Plan ID: {plan.id}")
            print(f"  Name: {plan.name}")
            print(f"  User: {user.email if user else 'Unknown'}")
            print(f"  Goal: {goal.name if goal else 'Unknown'}")
            print(f"  Duration: {plan.duration_weeks} weeks")
            print(f"  Start Date: {plan.start_date}")
            print(f"  Generated by AI: {plan.generated_by_ai}")
            print(f"  Workouts: {len(workouts)}")

            if len(workouts) == 0:
                print(f"  ⚠️  WARNING: This plan has NO workouts!")
            else:
                print(f"  ✅ This plan has workouts:")
                for w in workouts[:3]:  # Show first 3
                    print(f"     - Week {w.week_number}, Day {w.day_of_week}: {w.name}")
                if len(workouts) > 3:
                    print(f"     ... and {len(workouts) - 3} more workouts")

            print()

        # Summary
        total_workouts = db.query(Workout).count()
        plans_without_workouts = sum(1 for p in plans if len(p.workouts) == 0)

        print(f"\n{'='*80}")
        print(f"SUMMARY")
        print(f"{'='*80}")
        print(f"Total plans: {len(plans)}")
        print(f"Total workouts: {total_workouts}")
        print(f"Plans without workouts: {plans_without_workouts}")

        if plans_without_workouts > 0:
            print(f"\n⚠️  ISSUE DETECTED: {plans_without_workouts} plan(s) have no workouts!")
            print(f"\nThis is likely because:")
            print(f"  1. Ollama is not running (check: ollama serve)")
            print(f"  2. The AI response parsing failed")
            print(f"  3. The fallback plan generation failed")
            print(f"\nThe issue has been fixed in the code. Please:")
            print(f"  1. Delete the empty plan(s)")
            print(f"  2. Restart the backend server")
            print(f"  3. Generate a new plan")

    finally:
        db.close()

if __name__ == "__main__":
    check_plans()
